// Code generated by ent, DO NOT EDIT.

package paymentinvoice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldUserID, v))
}

// TitleName applies equality check predicate on the "title_name" field. It's identical to TitleNameEQ.
func TitleName(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldTitleName, v))
}

// TaxID applies equality check predicate on the "tax_id" field. It's identical to TaxIDEQ.
func TaxID(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldTaxID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldStatus, v))
}

// RequestedAt applies equality check predicate on the "requested_at" field. It's identical to RequestedAtEQ.
func RequestedAt(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldRequestedAt, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldIssuedAt, v))
}

// FailedAt applies equality check predicate on the "failed_at" field. It's identical to FailedAtEQ.
func FailedAt(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldFailedAt, v))
}

// FailedReason applies equality check predicate on the "failed_reason" field. It's identical to FailedReasonEQ.
func FailedReason(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldFailedReason, v))
}

// StorageProvider applies equality check predicate on the "storage_provider" field. It's identical to StorageProviderEQ.
func StorageProvider(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldStorageProvider, v))
}

// StorageKey applies equality check predicate on the "storage_key" field. It's identical to StorageKeyEQ.
func StorageKey(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldStorageKey, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldFileName, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldContentType, v))
}

// ByteSize applies equality check predicate on the "byte_size" field. It's identical to ByteSizeEQ.
func ByteSize(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldByteSize, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldSha256, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldUserID, vs...))
}

// TitleNameEQ applies the EQ predicate on the "title_name" field.
func TitleNameEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldTitleName, v))
}

// TitleNameNEQ applies the NEQ predicate on the "title_name" field.
func TitleNameNEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldTitleName, v))
}

// TitleNameIn applies the In predicate on the "title_name" field.
func TitleNameIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldTitleName, vs...))
}

// TitleNameNotIn applies the NotIn predicate on the "title_name" field.
func TitleNameNotIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldTitleName, vs...))
}

// TitleNameGT applies the GT predicate on the "title_name" field.
func TitleNameGT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldTitleName, v))
}

// TitleNameGTE applies the GTE predicate on the "title_name" field.
func TitleNameGTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldTitleName, v))
}

// TitleNameLT applies the LT predicate on the "title_name" field.
func TitleNameLT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldTitleName, v))
}

// TitleNameLTE applies the LTE predicate on the "title_name" field.
func TitleNameLTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldTitleName, v))
}

// TitleNameContains applies the Contains predicate on the "title_name" field.
func TitleNameContains(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContains(FieldTitleName, v))
}

// TitleNameHasPrefix applies the HasPrefix predicate on the "title_name" field.
func TitleNameHasPrefix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasPrefix(FieldTitleName, v))
}

// TitleNameHasSuffix applies the HasSuffix predicate on the "title_name" field.
func TitleNameHasSuffix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasSuffix(FieldTitleName, v))
}

// TitleNameEqualFold applies the EqualFold predicate on the "title_name" field.
func TitleNameEqualFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEqualFold(FieldTitleName, v))
}

// TitleNameContainsFold applies the ContainsFold predicate on the "title_name" field.
func TitleNameContainsFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContainsFold(FieldTitleName, v))
}

// TaxIDEQ applies the EQ predicate on the "tax_id" field.
func TaxIDEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldTaxID, v))
}

// TaxIDNEQ applies the NEQ predicate on the "tax_id" field.
func TaxIDNEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldTaxID, v))
}

// TaxIDIn applies the In predicate on the "tax_id" field.
func TaxIDIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldTaxID, vs...))
}

// TaxIDNotIn applies the NotIn predicate on the "tax_id" field.
func TaxIDNotIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldTaxID, vs...))
}

// TaxIDGT applies the GT predicate on the "tax_id" field.
func TaxIDGT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldTaxID, v))
}

// TaxIDGTE applies the GTE predicate on the "tax_id" field.
func TaxIDGTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldTaxID, v))
}

// TaxIDLT applies the LT predicate on the "tax_id" field.
func TaxIDLT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldTaxID, v))
}

// TaxIDLTE applies the LTE predicate on the "tax_id" field.
func TaxIDLTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldTaxID, v))
}

// TaxIDContains applies the Contains predicate on the "tax_id" field.
func TaxIDContains(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContains(FieldTaxID, v))
}

// TaxIDHasPrefix applies the HasPrefix predicate on the "tax_id" field.
func TaxIDHasPrefix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasPrefix(FieldTaxID, v))
}

// TaxIDHasSuffix applies the HasSuffix predicate on the "tax_id" field.
func TaxIDHasSuffix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasSuffix(FieldTaxID, v))
}

// TaxIDEqualFold applies the EqualFold predicate on the "tax_id" field.
func TaxIDEqualFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEqualFold(FieldTaxID, v))
}

// TaxIDContainsFold applies the ContainsFold predicate on the "tax_id" field.
func TaxIDContainsFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContainsFold(FieldTaxID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContainsFold(FieldStatus, v))
}

// RequestedAtEQ applies the EQ predicate on the "requested_at" field.
func RequestedAtEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldRequestedAt, v))
}

// RequestedAtNEQ applies the NEQ predicate on the "requested_at" field.
func RequestedAtNEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldRequestedAt, v))
}

// RequestedAtIn applies the In predicate on the "requested_at" field.
func RequestedAtIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldRequestedAt, vs...))
}

// RequestedAtNotIn applies the NotIn predicate on the "requested_at" field.
func RequestedAtNotIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldRequestedAt, vs...))
}

// RequestedAtGT applies the GT predicate on the "requested_at" field.
func RequestedAtGT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldRequestedAt, v))
}

// RequestedAtGTE applies the GTE predicate on the "requested_at" field.
func RequestedAtGTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldRequestedAt, v))
}

// RequestedAtLT applies the LT predicate on the "requested_at" field.
func RequestedAtLT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldRequestedAt, v))
}

// RequestedAtLTE applies the LTE predicate on the "requested_at" field.
func RequestedAtLTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldRequestedAt, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldIssuedAt, v))
}

// IssuedAtIsNil applies the IsNil predicate on the "issued_at" field.
func IssuedAtIsNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIsNull(FieldIssuedAt))
}

// IssuedAtNotNil applies the NotNil predicate on the "issued_at" field.
func IssuedAtNotNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotNull(FieldIssuedAt))
}

// FailedAtEQ applies the EQ predicate on the "failed_at" field.
func FailedAtEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldFailedAt, v))
}

// FailedAtNEQ applies the NEQ predicate on the "failed_at" field.
func FailedAtNEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldFailedAt, v))
}

// FailedAtIn applies the In predicate on the "failed_at" field.
func FailedAtIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldFailedAt, vs...))
}

// FailedAtNotIn applies the NotIn predicate on the "failed_at" field.
func FailedAtNotIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldFailedAt, vs...))
}

// FailedAtGT applies the GT predicate on the "failed_at" field.
func FailedAtGT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldFailedAt, v))
}

// FailedAtGTE applies the GTE predicate on the "failed_at" field.
func FailedAtGTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldFailedAt, v))
}

// FailedAtLT applies the LT predicate on the "failed_at" field.
func FailedAtLT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldFailedAt, v))
}

// FailedAtLTE applies the LTE predicate on the "failed_at" field.
func FailedAtLTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldFailedAt, v))
}

// FailedAtIsNil applies the IsNil predicate on the "failed_at" field.
func FailedAtIsNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIsNull(FieldFailedAt))
}

// FailedAtNotNil applies the NotNil predicate on the "failed_at" field.
func FailedAtNotNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotNull(FieldFailedAt))
}

// FailedReasonEQ applies the EQ predicate on the "failed_reason" field.
func FailedReasonEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldFailedReason, v))
}

// FailedReasonNEQ applies the NEQ predicate on the "failed_reason" field.
func FailedReasonNEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldFailedReason, v))
}

// FailedReasonIn applies the In predicate on the "failed_reason" field.
func FailedReasonIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldFailedReason, vs...))
}

// FailedReasonNotIn applies the NotIn predicate on the "failed_reason" field.
func FailedReasonNotIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldFailedReason, vs...))
}

// FailedReasonGT applies the GT predicate on the "failed_reason" field.
func FailedReasonGT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldFailedReason, v))
}

// FailedReasonGTE applies the GTE predicate on the "failed_reason" field.
func FailedReasonGTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldFailedReason, v))
}

// FailedReasonLT applies the LT predicate on the "failed_reason" field.
func FailedReasonLT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldFailedReason, v))
}

// FailedReasonLTE applies the LTE predicate on the "failed_reason" field.
func FailedReasonLTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldFailedReason, v))
}

// FailedReasonContains applies the Contains predicate on the "failed_reason" field.
func FailedReasonContains(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContains(FieldFailedReason, v))
}

// FailedReasonHasPrefix applies the HasPrefix predicate on the "failed_reason" field.
func FailedReasonHasPrefix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasPrefix(FieldFailedReason, v))
}

// FailedReasonHasSuffix applies the HasSuffix predicate on the "failed_reason" field.
func FailedReasonHasSuffix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasSuffix(FieldFailedReason, v))
}

// FailedReasonIsNil applies the IsNil predicate on the "failed_reason" field.
func FailedReasonIsNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIsNull(FieldFailedReason))
}

// FailedReasonNotNil applies the NotNil predicate on the "failed_reason" field.
func FailedReasonNotNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotNull(FieldFailedReason))
}

// FailedReasonEqualFold applies the EqualFold predicate on the "failed_reason" field.
func FailedReasonEqualFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEqualFold(FieldFailedReason, v))
}

// FailedReasonContainsFold applies the ContainsFold predicate on the "failed_reason" field.
func FailedReasonContainsFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContainsFold(FieldFailedReason, v))
}

// StorageProviderEQ applies the EQ predicate on the "storage_provider" field.
func StorageProviderEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldStorageProvider, v))
}

// StorageProviderNEQ applies the NEQ predicate on the "storage_provider" field.
func StorageProviderNEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldStorageProvider, v))
}

// StorageProviderIn applies the In predicate on the "storage_provider" field.
func StorageProviderIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldStorageProvider, vs...))
}

// StorageProviderNotIn applies the NotIn predicate on the "storage_provider" field.
func StorageProviderNotIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldStorageProvider, vs...))
}

// StorageProviderGT applies the GT predicate on the "storage_provider" field.
func StorageProviderGT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldStorageProvider, v))
}

// StorageProviderGTE applies the GTE predicate on the "storage_provider" field.
func StorageProviderGTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldStorageProvider, v))
}

// StorageProviderLT applies the LT predicate on the "storage_provider" field.
func StorageProviderLT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldStorageProvider, v))
}

// StorageProviderLTE applies the LTE predicate on the "storage_provider" field.
func StorageProviderLTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldStorageProvider, v))
}

// StorageProviderContains applies the Contains predicate on the "storage_provider" field.
func StorageProviderContains(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContains(FieldStorageProvider, v))
}

// StorageProviderHasPrefix applies the HasPrefix predicate on the "storage_provider" field.
func StorageProviderHasPrefix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasPrefix(FieldStorageProvider, v))
}

// StorageProviderHasSuffix applies the HasSuffix predicate on the "storage_provider" field.
func StorageProviderHasSuffix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasSuffix(FieldStorageProvider, v))
}

// StorageProviderEqualFold applies the EqualFold predicate on the "storage_provider" field.
func StorageProviderEqualFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEqualFold(FieldStorageProvider, v))
}

// StorageProviderContainsFold applies the ContainsFold predicate on the "storage_provider" field.
func StorageProviderContainsFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContainsFold(FieldStorageProvider, v))
}

// StorageKeyEQ applies the EQ predicate on the "storage_key" field.
func StorageKeyEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldStorageKey, v))
}

// StorageKeyNEQ applies the NEQ predicate on the "storage_key" field.
func StorageKeyNEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldStorageKey, v))
}

// StorageKeyIn applies the In predicate on the "storage_key" field.
func StorageKeyIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldStorageKey, vs...))
}

// StorageKeyNotIn applies the NotIn predicate on the "storage_key" field.
func StorageKeyNotIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldStorageKey, vs...))
}

// StorageKeyGT applies the GT predicate on the "storage_key" field.
func StorageKeyGT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldStorageKey, v))
}

// StorageKeyGTE applies the GTE predicate on the "storage_key" field.
func StorageKeyGTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldStorageKey, v))
}

// StorageKeyLT applies the LT predicate on the "storage_key" field.
func StorageKeyLT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldStorageKey, v))
}

// StorageKeyLTE applies the LTE predicate on the "storage_key" field.
func StorageKeyLTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldStorageKey, v))
}

// StorageKeyContains applies the Contains predicate on the "storage_key" field.
func StorageKeyContains(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContains(FieldStorageKey, v))
}

// StorageKeyHasPrefix applies the HasPrefix predicate on the "storage_key" field.
func StorageKeyHasPrefix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasPrefix(FieldStorageKey, v))
}

// StorageKeyHasSuffix applies the HasSuffix predicate on the "storage_key" field.
func StorageKeyHasSuffix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasSuffix(FieldStorageKey, v))
}

// StorageKeyIsNil applies the IsNil predicate on the "storage_key" field.
func StorageKeyIsNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIsNull(FieldStorageKey))
}

// StorageKeyNotNil applies the NotNil predicate on the "storage_key" field.
func StorageKeyNotNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotNull(FieldStorageKey))
}

// StorageKeyEqualFold applies the EqualFold predicate on the "storage_key" field.
func StorageKeyEqualFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEqualFold(FieldStorageKey, v))
}

// StorageKeyContainsFold applies the ContainsFold predicate on the "storage_key" field.
func StorageKeyContainsFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContainsFold(FieldStorageKey, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameIsNil applies the IsNil predicate on the "file_name" field.
func FileNameIsNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIsNull(FieldFileName))
}

// FileNameNotNil applies the NotNil predicate on the "file_name" field.
func FileNameNotNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotNull(FieldFileName))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContainsFold(FieldFileName, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeIsNil applies the IsNil predicate on the "content_type" field.
func ContentTypeIsNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIsNull(FieldContentType))
}

// ContentTypeNotNil applies the NotNil predicate on the "content_type" field.
func ContentTypeNotNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotNull(FieldContentType))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContainsFold(FieldContentType, v))
}

// ByteSizeEQ applies the EQ predicate on the "byte_size" field.
func ByteSizeEQ(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldByteSize, v))
}

// ByteSizeNEQ applies the NEQ predicate on the "byte_size" field.
func ByteSizeNEQ(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldByteSize, v))
}

// ByteSizeIn applies the In predicate on the "byte_size" field.
func ByteSizeIn(vs ...int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldByteSize, vs...))
}

// ByteSizeNotIn applies the NotIn predicate on the "byte_size" field.
func ByteSizeNotIn(vs ...int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldByteSize, vs...))
}

// ByteSizeGT applies the GT predicate on the "byte_size" field.
func ByteSizeGT(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldByteSize, v))
}

// ByteSizeGTE applies the GTE predicate on the "byte_size" field.
func ByteSizeGTE(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldByteSize, v))
}

// ByteSizeLT applies the LT predicate on the "byte_size" field.
func ByteSizeLT(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldByteSize, v))
}

// ByteSizeLTE applies the LTE predicate on the "byte_size" field.
func ByteSizeLTE(v int64) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldByteSize, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256IsNil applies the IsNil predicate on the "sha256" field.
func Sha256IsNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIsNull(FieldSha256))
}

// Sha256NotNil applies the NotNil predicate on the "sha256" field.
func Sha256NotNil() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotNull(FieldSha256))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldContainsFold(FieldSha256, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.PaymentOrder) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PaymentInvoice {
	return predicate.PaymentInvoice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentInvoice) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentInvoice) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentInvoice) predicate.PaymentInvoice {
	return predicate.PaymentInvoice(sql.NotPredicates(p))
}
