// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoice"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentInvoice is the model entity for the PaymentInvoice schema.
type PaymentInvoice struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// TitleName holds the value of the "title_name" field.
	TitleName string `json:"title_name,omitempty"`
	// TaxID holds the value of the "tax_id" field.
	TaxID string `json:"tax_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RequestedAt holds the value of the "requested_at" field.
	RequestedAt time.Time `json:"requested_at,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt *time.Time `json:"issued_at,omitempty"`
	// FailedAt holds the value of the "failed_at" field.
	FailedAt *time.Time `json:"failed_at,omitempty"`
	// FailedReason holds the value of the "failed_reason" field.
	FailedReason *string `json:"failed_reason,omitempty"`
	// StorageProvider holds the value of the "storage_provider" field.
	StorageProvider string `json:"storage_provider,omitempty"`
	// StorageKey holds the value of the "storage_key" field.
	StorageKey *string `json:"storage_key,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName *string `json:"file_name,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType *string `json:"content_type,omitempty"`
	// ByteSize holds the value of the "byte_size" field.
	ByteSize int64 `json:"byte_size,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 *string `json:"sha256,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentInvoiceQuery when eager-loading is set.
	Edges        PaymentInvoiceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentInvoiceEdges holds the relations/edges for other nodes in the graph.
type PaymentInvoiceEdges struct {
	// Order holds the value of the order edge.
	Order *PaymentOrder `json:"order,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentInvoiceEdges) OrderOrErr() (*PaymentOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentInvoiceEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentInvoice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentinvoice.FieldID, paymentinvoice.FieldOrderID, paymentinvoice.FieldUserID, paymentinvoice.FieldByteSize:
			values[i] = new(sql.NullInt64)
		case paymentinvoice.FieldTitleName, paymentinvoice.FieldTaxID, paymentinvoice.FieldStatus, paymentinvoice.FieldFailedReason, paymentinvoice.FieldStorageProvider, paymentinvoice.FieldStorageKey, paymentinvoice.FieldFileName, paymentinvoice.FieldContentType, paymentinvoice.FieldSha256:
			values[i] = new(sql.NullString)
		case paymentinvoice.FieldRequestedAt, paymentinvoice.FieldIssuedAt, paymentinvoice.FieldFailedAt, paymentinvoice.FieldCreatedAt, paymentinvoice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentInvoice fields.
func (_m *PaymentInvoice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentinvoice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentinvoice.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case paymentinvoice.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case paymentinvoice.FieldTitleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_name", values[i])
			} else if value.Valid {
				_m.TitleName = value.String
			}
		case paymentinvoice.FieldTaxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_id", values[i])
			} else if value.Valid {
				_m.TaxID = value.String
			}
		case paymentinvoice.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentinvoice.FieldRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field requested_at", values[i])
			} else if value.Valid {
				_m.RequestedAt = value.Time
			}
		case paymentinvoice.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = new(time.Time)
				*_m.IssuedAt = value.Time
			}
		case paymentinvoice.FieldFailedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field failed_at", values[i])
			} else if value.Valid {
				_m.FailedAt = new(time.Time)
				*_m.FailedAt = value.Time
			}
		case paymentinvoice.FieldFailedReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failed_reason", values[i])
			} else if value.Valid {
				_m.FailedReason = new(string)
				*_m.FailedReason = value.String
			}
		case paymentinvoice.FieldStorageProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_provider", values[i])
			} else if value.Valid {
				_m.StorageProvider = value.String
			}
		case paymentinvoice.FieldStorageKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_key", values[i])
			} else if value.Valid {
				_m.StorageKey = new(string)
				*_m.StorageKey = value.String
			}
		case paymentinvoice.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = new(string)
				*_m.FileName = value.String
			}
		case paymentinvoice.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = new(string)
				*_m.ContentType = value.String
			}
		case paymentinvoice.FieldByteSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field byte_size", values[i])
			} else if value.Valid {
				_m.ByteSize = value.Int64
			}
		case paymentinvoice.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = new(string)
				*_m.Sha256 = value.String
			}
		case paymentinvoice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentinvoice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentInvoice.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentInvoice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrder queries the "order" edge of the PaymentInvoice entity.
func (_m *PaymentInvoice) QueryOrder() *PaymentOrderQuery {
	return NewPaymentInvoiceClient(_m.config).QueryOrder(_m)
}

// QueryUser queries the "user" edge of the PaymentInvoice entity.
func (_m *PaymentInvoice) QueryUser() *UserQuery {
	return NewPaymentInvoiceClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PaymentInvoice.
// Note that you need to call PaymentInvoice.Unwrap() before calling this method if this PaymentInvoice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentInvoice) Update() *PaymentInvoiceUpdateOne {
	return NewPaymentInvoiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentInvoice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentInvoice) Unwrap() *PaymentInvoice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentInvoice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentInvoice) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentInvoice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("title_name=")
	builder.WriteString(_m.TitleName)
	builder.WriteString(", ")
	builder.WriteString("tax_id=")
	builder.WriteString(_m.TaxID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("requested_at=")
	builder.WriteString(_m.RequestedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.IssuedAt; v != nil {
		builder.WriteString("issued_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FailedAt; v != nil {
		builder.WriteString("failed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FailedReason; v != nil {
		builder.WriteString("failed_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("storage_provider=")
	builder.WriteString(_m.StorageProvider)
	builder.WriteString(", ")
	if v := _m.StorageKey; v != nil {
		builder.WriteString("storage_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FileName; v != nil {
		builder.WriteString("file_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContentType; v != nil {
		builder.WriteString("content_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("byte_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.ByteSize))
	builder.WriteString(", ")
	if v := _m.Sha256; v != nil {
		builder.WriteString("sha256=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentInvoices is a parsable slice of PaymentInvoice.
type PaymentInvoices []*PaymentInvoice
