// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoice"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentInvoiceUpdate is the builder for updating PaymentInvoice entities.
type PaymentInvoiceUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentInvoiceMutation
}

// Where appends a list predicates to the PaymentInvoiceUpdate builder.
func (_u *PaymentInvoiceUpdate) Where(ps ...predicate.PaymentInvoice) *PaymentInvoiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *PaymentInvoiceUpdate) SetOrderID(v int64) *PaymentInvoiceUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableOrderID(v *int64) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentInvoiceUpdate) SetUserID(v int64) *PaymentInvoiceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableUserID(v *int64) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitleName sets the "title_name" field.
func (_u *PaymentInvoiceUpdate) SetTitleName(v string) *PaymentInvoiceUpdate {
	_u.mutation.SetTitleName(v)
	return _u
}

// SetNillableTitleName sets the "title_name" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableTitleName(v *string) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetTitleName(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *PaymentInvoiceUpdate) SetTaxID(v string) *PaymentInvoiceUpdate {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableTaxID(v *string) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentInvoiceUpdate) SetStatus(v string) *PaymentInvoiceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableStatus(v *string) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *PaymentInvoiceUpdate) SetRequestedAt(v time.Time) *PaymentInvoiceUpdate {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableRequestedAt(v *time.Time) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *PaymentInvoiceUpdate) SetIssuedAt(v time.Time) *PaymentInvoiceUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableIssuedAt(v *time.Time) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *PaymentInvoiceUpdate) ClearIssuedAt() *PaymentInvoiceUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetFailedAt sets the "failed_at" field.
func (_u *PaymentInvoiceUpdate) SetFailedAt(v time.Time) *PaymentInvoiceUpdate {
	_u.mutation.SetFailedAt(v)
	return _u
}

// SetNillableFailedAt sets the "failed_at" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableFailedAt(v *time.Time) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetFailedAt(*v)
	}
	return _u
}

// ClearFailedAt clears the value of the "failed_at" field.
func (_u *PaymentInvoiceUpdate) ClearFailedAt() *PaymentInvoiceUpdate {
	_u.mutation.ClearFailedAt()
	return _u
}

// SetFailedReason sets the "failed_reason" field.
func (_u *PaymentInvoiceUpdate) SetFailedReason(v string) *PaymentInvoiceUpdate {
	_u.mutation.SetFailedReason(v)
	return _u
}

// SetNillableFailedReason sets the "failed_reason" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableFailedReason(v *string) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetFailedReason(*v)
	}
	return _u
}

// ClearFailedReason clears the value of the "failed_reason" field.
func (_u *PaymentInvoiceUpdate) ClearFailedReason() *PaymentInvoiceUpdate {
	_u.mutation.ClearFailedReason()
	return _u
}

// SetStorageProvider sets the "storage_provider" field.
func (_u *PaymentInvoiceUpdate) SetStorageProvider(v string) *PaymentInvoiceUpdate {
	_u.mutation.SetStorageProvider(v)
	return _u
}

// SetNillableStorageProvider sets the "storage_provider" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableStorageProvider(v *string) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetStorageProvider(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *PaymentInvoiceUpdate) SetStorageKey(v string) *PaymentInvoiceUpdate {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableStorageKey(v *string) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// ClearStorageKey clears the value of the "storage_key" field.
func (_u *PaymentInvoiceUpdate) ClearStorageKey() *PaymentInvoiceUpdate {
	_u.mutation.ClearStorageKey()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *PaymentInvoiceUpdate) SetFileName(v string) *PaymentInvoiceUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableFileName(v *string) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// ClearFileName clears the value of the "file_name" field.
func (_u *PaymentInvoiceUpdate) ClearFileName() *PaymentInvoiceUpdate {
	_u.mutation.ClearFileName()
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *PaymentInvoiceUpdate) SetContentType(v string) *PaymentInvoiceUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableContentType(v *string) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// ClearContentType clears the value of the "content_type" field.
func (_u *PaymentInvoiceUpdate) ClearContentType() *PaymentInvoiceUpdate {
	_u.mutation.ClearContentType()
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *PaymentInvoiceUpdate) SetByteSize(v int64) *PaymentInvoiceUpdate {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableByteSize(v *int64) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *PaymentInvoiceUpdate) AddByteSize(v int64) *PaymentInvoiceUpdate {
	_u.mutation.AddByteSize(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *PaymentInvoiceUpdate) SetSha256(v string) *PaymentInvoiceUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *PaymentInvoiceUpdate) SetNillableSha256(v *string) *PaymentInvoiceUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *PaymentInvoiceUpdate) ClearSha256() *PaymentInvoiceUpdate {
	_u.mutation.ClearSha256()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentInvoiceUpdate) SetUpdatedAt(v time.Time) *PaymentInvoiceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *PaymentInvoiceUpdate) SetOrder(v *PaymentOrder) *PaymentInvoiceUpdate {
	return _u.SetOrderID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentInvoiceUpdate) SetUser(v *User) *PaymentInvoiceUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentInvoiceMutation object of the builder.
func (_u *PaymentInvoiceUpdate) Mutation() *PaymentInvoiceMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *PaymentInvoiceUpdate) ClearOrder() *PaymentInvoiceUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentInvoiceUpdate) ClearUser() *PaymentInvoiceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentInvoiceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentInvoiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentInvoiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentInvoiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentInvoiceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentinvoice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentInvoiceUpdate) check() error {
	if v, ok := _u.mutation.TitleName(); ok {
		if err := paymentinvoice.TitleNameValidator(v); err != nil {
			return &ValidationError{Name: "title_name", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.title_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := paymentinvoice.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentinvoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageProvider(); ok {
		if err := paymentinvoice.StorageProviderValidator(v); err != nil {
			return &ValidationError{Name: "storage_provider", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.storage_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := paymentinvoice.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := paymentinvoice.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := paymentinvoice.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.sha256": %w`, err)}
		}
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentInvoice.order"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentInvoice.user"`)
	}
	return nil
}

func (_u *PaymentInvoiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentinvoice.Table, paymentinvoice.Columns, sqlgraph.NewFieldSpec(paymentinvoice.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TitleName(); ok {
		_spec.SetField(paymentinvoice.FieldTitleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(paymentinvoice.FieldTaxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentinvoice.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(paymentinvoice.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(paymentinvoice.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(paymentinvoice.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedAt(); ok {
		_spec.SetField(paymentinvoice.FieldFailedAt, field.TypeTime, value)
	}
	if _u.mutation.FailedAtCleared() {
		_spec.ClearField(paymentinvoice.FieldFailedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedReason(); ok {
		_spec.SetField(paymentinvoice.FieldFailedReason, field.TypeString, value)
	}
	if _u.mutation.FailedReasonCleared() {
		_spec.ClearField(paymentinvoice.FieldFailedReason, field.TypeString)
	}
	if value, ok := _u.mutation.StorageProvider(); ok {
		_spec.SetField(paymentinvoice.FieldStorageProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(paymentinvoice.FieldStorageKey, field.TypeString, value)
	}
	if _u.mutation.StorageKeyCleared() {
		_spec.ClearField(paymentinvoice.FieldStorageKey, field.TypeString)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(paymentinvoice.FieldFileName, field.TypeString, value)
	}
	if _u.mutation.FileNameCleared() {
		_spec.ClearField(paymentinvoice.FieldFileName, field.TypeString)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(paymentinvoice.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.ContentTypeCleared() {
		_spec.ClearField(paymentinvoice.FieldContentType, field.TypeString)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(paymentinvoice.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(paymentinvoice.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(paymentinvoice.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(paymentinvoice.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentinvoice.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentinvoice.OrderTable,
			Columns: []string{paymentinvoice.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentinvoice.OrderTable,
			Columns: []string{paymentinvoice.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentinvoice.UserTable,
			Columns: []string{paymentinvoice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentinvoice.UserTable,
			Columns: []string{paymentinvoice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentinvoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentInvoiceUpdateOne is the builder for updating a single PaymentInvoice entity.
type PaymentInvoiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentInvoiceMutation
}

// SetOrderID sets the "order_id" field.
func (_u *PaymentInvoiceUpdateOne) SetOrderID(v int64) *PaymentInvoiceUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableOrderID(v *int64) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentInvoiceUpdateOne) SetUserID(v int64) *PaymentInvoiceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableUserID(v *int64) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitleName sets the "title_name" field.
func (_u *PaymentInvoiceUpdateOne) SetTitleName(v string) *PaymentInvoiceUpdateOne {
	_u.mutation.SetTitleName(v)
	return _u
}

// SetNillableTitleName sets the "title_name" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableTitleName(v *string) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetTitleName(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *PaymentInvoiceUpdateOne) SetTaxID(v string) *PaymentInvoiceUpdateOne {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableTaxID(v *string) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentInvoiceUpdateOne) SetStatus(v string) *PaymentInvoiceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableStatus(v *string) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *PaymentInvoiceUpdateOne) SetRequestedAt(v time.Time) *PaymentInvoiceUpdateOne {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableRequestedAt(v *time.Time) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *PaymentInvoiceUpdateOne) SetIssuedAt(v time.Time) *PaymentInvoiceUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableIssuedAt(v *time.Time) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *PaymentInvoiceUpdateOne) ClearIssuedAt() *PaymentInvoiceUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetFailedAt sets the "failed_at" field.
func (_u *PaymentInvoiceUpdateOne) SetFailedAt(v time.Time) *PaymentInvoiceUpdateOne {
	_u.mutation.SetFailedAt(v)
	return _u
}

// SetNillableFailedAt sets the "failed_at" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableFailedAt(v *time.Time) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetFailedAt(*v)
	}
	return _u
}

// ClearFailedAt clears the value of the "failed_at" field.
func (_u *PaymentInvoiceUpdateOne) ClearFailedAt() *PaymentInvoiceUpdateOne {
	_u.mutation.ClearFailedAt()
	return _u
}

// SetFailedReason sets the "failed_reason" field.
func (_u *PaymentInvoiceUpdateOne) SetFailedReason(v string) *PaymentInvoiceUpdateOne {
	_u.mutation.SetFailedReason(v)
	return _u
}

// SetNillableFailedReason sets the "failed_reason" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableFailedReason(v *string) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetFailedReason(*v)
	}
	return _u
}

// ClearFailedReason clears the value of the "failed_reason" field.
func (_u *PaymentInvoiceUpdateOne) ClearFailedReason() *PaymentInvoiceUpdateOne {
	_u.mutation.ClearFailedReason()
	return _u
}

// SetStorageProvider sets the "storage_provider" field.
func (_u *PaymentInvoiceUpdateOne) SetStorageProvider(v string) *PaymentInvoiceUpdateOne {
	_u.mutation.SetStorageProvider(v)
	return _u
}

// SetNillableStorageProvider sets the "storage_provider" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableStorageProvider(v *string) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetStorageProvider(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *PaymentInvoiceUpdateOne) SetStorageKey(v string) *PaymentInvoiceUpdateOne {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableStorageKey(v *string) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// ClearStorageKey clears the value of the "storage_key" field.
func (_u *PaymentInvoiceUpdateOne) ClearStorageKey() *PaymentInvoiceUpdateOne {
	_u.mutation.ClearStorageKey()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *PaymentInvoiceUpdateOne) SetFileName(v string) *PaymentInvoiceUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableFileName(v *string) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// ClearFileName clears the value of the "file_name" field.
func (_u *PaymentInvoiceUpdateOne) ClearFileName() *PaymentInvoiceUpdateOne {
	_u.mutation.ClearFileName()
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *PaymentInvoiceUpdateOne) SetContentType(v string) *PaymentInvoiceUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableContentType(v *string) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// ClearContentType clears the value of the "content_type" field.
func (_u *PaymentInvoiceUpdateOne) ClearContentType() *PaymentInvoiceUpdateOne {
	_u.mutation.ClearContentType()
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *PaymentInvoiceUpdateOne) SetByteSize(v int64) *PaymentInvoiceUpdateOne {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableByteSize(v *int64) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *PaymentInvoiceUpdateOne) AddByteSize(v int64) *PaymentInvoiceUpdateOne {
	_u.mutation.AddByteSize(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *PaymentInvoiceUpdateOne) SetSha256(v string) *PaymentInvoiceUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *PaymentInvoiceUpdateOne) SetNillableSha256(v *string) *PaymentInvoiceUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *PaymentInvoiceUpdateOne) ClearSha256() *PaymentInvoiceUpdateOne {
	_u.mutation.ClearSha256()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentInvoiceUpdateOne) SetUpdatedAt(v time.Time) *PaymentInvoiceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *PaymentInvoiceUpdateOne) SetOrder(v *PaymentOrder) *PaymentInvoiceUpdateOne {
	return _u.SetOrderID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentInvoiceUpdateOne) SetUser(v *User) *PaymentInvoiceUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentInvoiceMutation object of the builder.
func (_u *PaymentInvoiceUpdateOne) Mutation() *PaymentInvoiceMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *PaymentInvoiceUpdateOne) ClearOrder() *PaymentInvoiceUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentInvoiceUpdateOne) ClearUser() *PaymentInvoiceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaymentInvoiceUpdate builder.
func (_u *PaymentInvoiceUpdateOne) Where(ps ...predicate.PaymentInvoice) *PaymentInvoiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentInvoiceUpdateOne) Select(field string, fields ...string) *PaymentInvoiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentInvoice entity.
func (_u *PaymentInvoiceUpdateOne) Save(ctx context.Context) (*PaymentInvoice, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentInvoiceUpdateOne) SaveX(ctx context.Context) *PaymentInvoice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentInvoiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentInvoiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentInvoiceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentinvoice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentInvoiceUpdateOne) check() error {
	if v, ok := _u.mutation.TitleName(); ok {
		if err := paymentinvoice.TitleNameValidator(v); err != nil {
			return &ValidationError{Name: "title_name", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.title_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := paymentinvoice.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentinvoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageProvider(); ok {
		if err := paymentinvoice.StorageProviderValidator(v); err != nil {
			return &ValidationError{Name: "storage_provider", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.storage_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := paymentinvoice.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := paymentinvoice.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := paymentinvoice.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.sha256": %w`, err)}
		}
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentInvoice.order"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentInvoice.user"`)
	}
	return nil
}

func (_u *PaymentInvoiceUpdateOne) sqlSave(ctx context.Context) (_node *PaymentInvoice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentinvoice.Table, paymentinvoice.Columns, sqlgraph.NewFieldSpec(paymentinvoice.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentInvoice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentinvoice.FieldID)
		for _, f := range fields {
			if !paymentinvoice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentinvoice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TitleName(); ok {
		_spec.SetField(paymentinvoice.FieldTitleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(paymentinvoice.FieldTaxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentinvoice.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(paymentinvoice.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(paymentinvoice.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(paymentinvoice.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedAt(); ok {
		_spec.SetField(paymentinvoice.FieldFailedAt, field.TypeTime, value)
	}
	if _u.mutation.FailedAtCleared() {
		_spec.ClearField(paymentinvoice.FieldFailedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedReason(); ok {
		_spec.SetField(paymentinvoice.FieldFailedReason, field.TypeString, value)
	}
	if _u.mutation.FailedReasonCleared() {
		_spec.ClearField(paymentinvoice.FieldFailedReason, field.TypeString)
	}
	if value, ok := _u.mutation.StorageProvider(); ok {
		_spec.SetField(paymentinvoice.FieldStorageProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(paymentinvoice.FieldStorageKey, field.TypeString, value)
	}
	if _u.mutation.StorageKeyCleared() {
		_spec.ClearField(paymentinvoice.FieldStorageKey, field.TypeString)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(paymentinvoice.FieldFileName, field.TypeString, value)
	}
	if _u.mutation.FileNameCleared() {
		_spec.ClearField(paymentinvoice.FieldFileName, field.TypeString)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(paymentinvoice.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.ContentTypeCleared() {
		_spec.ClearField(paymentinvoice.FieldContentType, field.TypeString)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(paymentinvoice.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(paymentinvoice.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(paymentinvoice.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(paymentinvoice.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentinvoice.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentinvoice.OrderTable,
			Columns: []string{paymentinvoice.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentinvoice.OrderTable,
			Columns: []string{paymentinvoice.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentinvoice.UserTable,
			Columns: []string{paymentinvoice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentinvoice.UserTable,
			Columns: []string{paymentinvoice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentInvoice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentinvoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
