// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoice"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentInvoiceCreate is the builder for creating a PaymentInvoice entity.
type PaymentInvoiceCreate struct {
	config
	mutation *PaymentInvoiceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *PaymentInvoiceCreate) SetUserID(v int64) *PaymentInvoiceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitleName sets the "title_name" field.
func (_c *PaymentInvoiceCreate) SetTitleName(v string) *PaymentInvoiceCreate {
	_c.mutation.SetTitleName(v)
	return _c
}

// SetTaxID sets the "tax_id" field.
func (_c *PaymentInvoiceCreate) SetTaxID(v string) *PaymentInvoiceCreate {
	_c.mutation.SetTaxID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentInvoiceCreate) SetStatus(v string) *PaymentInvoiceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableStatus(v *string) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRequestedAt sets the "requested_at" field.
func (_c *PaymentInvoiceCreate) SetRequestedAt(v time.Time) *PaymentInvoiceCreate {
	_c.mutation.SetRequestedAt(v)
	return _c
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableRequestedAt(v *time.Time) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetRequestedAt(*v)
	}
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *PaymentInvoiceCreate) SetIssuedAt(v time.Time) *PaymentInvoiceCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableIssuedAt(v *time.Time) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetFailedAt sets the "failed_at" field.
func (_c *PaymentInvoiceCreate) SetFailedAt(v time.Time) *PaymentInvoiceCreate {
	_c.mutation.SetFailedAt(v)
	return _c
}

// SetNillableFailedAt sets the "failed_at" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableFailedAt(v *time.Time) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetFailedAt(*v)
	}
	return _c
}

// SetFailedReason sets the "failed_reason" field.
func (_c *PaymentInvoiceCreate) SetFailedReason(v string) *PaymentInvoiceCreate {
	_c.mutation.SetFailedReason(v)
	return _c
}

// SetNillableFailedReason sets the "failed_reason" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableFailedReason(v *string) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetFailedReason(*v)
	}
	return _c
}

// SetStorageProvider sets the "storage_provider" field.
func (_c *PaymentInvoiceCreate) SetStorageProvider(v string) *PaymentInvoiceCreate {
	_c.mutation.SetStorageProvider(v)
	return _c
}

// SetNillableStorageProvider sets the "storage_provider" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableStorageProvider(v *string) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetStorageProvider(*v)
	}
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *PaymentInvoiceCreate) SetStorageKey(v string) *PaymentInvoiceCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableStorageKey(v *string) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetStorageKey(*v)
	}
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *PaymentInvoiceCreate) SetFileName(v string) *PaymentInvoiceCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableFileName(v *string) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetFileName(*v)
	}
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *PaymentInvoiceCreate) SetContentType(v string) *PaymentInvoiceCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableContentType(v *string) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetByteSize sets the "byte_size" field.
func (_c *PaymentInvoiceCreate) SetByteSize(v int64) *PaymentInvoiceCreate {
	_c.mutation.SetByteSize(v)
	return _c
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableByteSize(v *int64) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetByteSize(*v)
	}
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *PaymentInvoiceCreate) SetSha256(v string) *PaymentInvoiceCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableSha256(v *string) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetSha256(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentInvoiceCreate) SetCreatedAt(v time.Time) *PaymentInvoiceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableCreatedAt(v *time.Time) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentInvoiceCreate) SetUpdatedAt(v time.Time) *PaymentInvoiceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentInvoiceCreate) SetNillableUpdatedAt(v *time.Time) *PaymentInvoiceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddOrderIDs adds the "orders" edge to the PaymentOrder entity by IDs.
func (_c *PaymentInvoiceCreate) AddOrderIDs(ids ...int64) *PaymentInvoiceCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the PaymentOrder entity.
func (_c *PaymentInvoiceCreate) AddOrders(v ...*PaymentOrder) *PaymentInvoiceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentInvoiceCreate) SetUser(v *User) *PaymentInvoiceCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaymentInvoiceMutation object of the builder.
func (_c *PaymentInvoiceCreate) Mutation() *PaymentInvoiceMutation {
	return _c.mutation
}

// Save creates the PaymentInvoice in the database.
func (_c *PaymentInvoiceCreate) Save(ctx context.Context) (*PaymentInvoice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentInvoiceCreate) SaveX(ctx context.Context) *PaymentInvoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentInvoiceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentInvoiceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentInvoiceCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentinvoice.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RequestedAt(); !ok {
		v := paymentinvoice.DefaultRequestedAt()
		_c.mutation.SetRequestedAt(v)
	}
	if _, ok := _c.mutation.StorageProvider(); !ok {
		v := paymentinvoice.DefaultStorageProvider
		_c.mutation.SetStorageProvider(v)
	}
	if _, ok := _c.mutation.ByteSize(); !ok {
		v := paymentinvoice.DefaultByteSize
		_c.mutation.SetByteSize(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentinvoice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentinvoice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentInvoiceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentInvoice.user_id"`)}
	}
	if _, ok := _c.mutation.TitleName(); !ok {
		return &ValidationError{Name: "title_name", err: errors.New(`ent: missing required field "PaymentInvoice.title_name"`)}
	}
	if v, ok := _c.mutation.TitleName(); ok {
		if err := paymentinvoice.TitleNameValidator(v); err != nil {
			return &ValidationError{Name: "title_name", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.title_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxID(); !ok {
		return &ValidationError{Name: "tax_id", err: errors.New(`ent: missing required field "PaymentInvoice.tax_id"`)}
	}
	if v, ok := _c.mutation.TaxID(); ok {
		if err := paymentinvoice.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.tax_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentInvoice.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentinvoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requested_at", err: errors.New(`ent: missing required field "PaymentInvoice.requested_at"`)}
	}
	if _, ok := _c.mutation.StorageProvider(); !ok {
		return &ValidationError{Name: "storage_provider", err: errors.New(`ent: missing required field "PaymentInvoice.storage_provider"`)}
	}
	if v, ok := _c.mutation.StorageProvider(); ok {
		if err := paymentinvoice.StorageProviderValidator(v); err != nil {
			return &ValidationError{Name: "storage_provider", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.storage_provider": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := paymentinvoice.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.file_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := paymentinvoice.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ByteSize(); !ok {
		return &ValidationError{Name: "byte_size", err: errors.New(`ent: missing required field "PaymentInvoice.byte_size"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := paymentinvoice.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoice.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentInvoice.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentInvoice.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentInvoice.user"`)}
	}
	return nil
}

func (_c *PaymentInvoiceCreate) sqlSave(ctx context.Context) (*PaymentInvoice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentInvoiceCreate) createSpec() (*PaymentInvoice, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentInvoice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentinvoice.Table, sqlgraph.NewFieldSpec(paymentinvoice.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TitleName(); ok {
		_spec.SetField(paymentinvoice.FieldTitleName, field.TypeString, value)
		_node.TitleName = value
	}
	if value, ok := _c.mutation.TaxID(); ok {
		_spec.SetField(paymentinvoice.FieldTaxID, field.TypeString, value)
		_node.TaxID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentinvoice.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RequestedAt(); ok {
		_spec.SetField(paymentinvoice.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(paymentinvoice.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.FailedAt(); ok {
		_spec.SetField(paymentinvoice.FieldFailedAt, field.TypeTime, value)
		_node.FailedAt = &value
	}
	if value, ok := _c.mutation.FailedReason(); ok {
		_spec.SetField(paymentinvoice.FieldFailedReason, field.TypeString, value)
		_node.FailedReason = &value
	}
	if value, ok := _c.mutation.StorageProvider(); ok {
		_spec.SetField(paymentinvoice.FieldStorageProvider, field.TypeString, value)
		_node.StorageProvider = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(paymentinvoice.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = &value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(paymentinvoice.FieldFileName, field.TypeString, value)
		_node.FileName = &value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(paymentinvoice.FieldContentType, field.TypeString, value)
		_node.ContentType = &value
	}
	if value, ok := _c.mutation.ByteSize(); ok {
		_spec.SetField(paymentinvoice.FieldByteSize, field.TypeInt64, value)
		_node.ByteSize = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(paymentinvoice.FieldSha256, field.TypeString, value)
		_node.Sha256 = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentinvoice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentinvoice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentinvoice.OrdersTable,
			Columns: []string{paymentinvoice.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentinvoice.UserTable,
			Columns: []string{paymentinvoice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentInvoice.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentInvoiceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentInvoiceCreate) OnConflict(opts ...sql.ConflictOption) *PaymentInvoiceUpsertOne {
	_c.conflict = opts
	return &PaymentInvoiceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentInvoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentInvoiceCreate) OnConflictColumns(columns ...string) *PaymentInvoiceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentInvoiceUpsertOne{
		create: _c,
	}
}

type (
	// PaymentInvoiceUpsertOne is the builder for "upsert"-ing
	//  one PaymentInvoice node.
	PaymentInvoiceUpsertOne struct {
		create *PaymentInvoiceCreate
	}

	// PaymentInvoiceUpsert is the "OnConflict" setter.
	PaymentInvoiceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *PaymentInvoiceUpsert) SetUserID(v int64) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateUserID() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldUserID)
	return u
}

// SetTitleName sets the "title_name" field.
func (u *PaymentInvoiceUpsert) SetTitleName(v string) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldTitleName, v)
	return u
}

// UpdateTitleName sets the "title_name" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateTitleName() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldTitleName)
	return u
}

// SetTaxID sets the "tax_id" field.
func (u *PaymentInvoiceUpsert) SetTaxID(v string) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldTaxID, v)
	return u
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateTaxID() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldTaxID)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentInvoiceUpsert) SetStatus(v string) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateStatus() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldStatus)
	return u
}

// SetRequestedAt sets the "requested_at" field.
func (u *PaymentInvoiceUpsert) SetRequestedAt(v time.Time) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldRequestedAt, v)
	return u
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateRequestedAt() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldRequestedAt)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *PaymentInvoiceUpsert) SetIssuedAt(v time.Time) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateIssuedAt() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldIssuedAt)
	return u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *PaymentInvoiceUpsert) ClearIssuedAt() *PaymentInvoiceUpsert {
	u.SetNull(paymentinvoice.FieldIssuedAt)
	return u
}

// SetFailedAt sets the "failed_at" field.
func (u *PaymentInvoiceUpsert) SetFailedAt(v time.Time) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldFailedAt, v)
	return u
}

// UpdateFailedAt sets the "failed_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateFailedAt() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldFailedAt)
	return u
}

// ClearFailedAt clears the value of the "failed_at" field.
func (u *PaymentInvoiceUpsert) ClearFailedAt() *PaymentInvoiceUpsert {
	u.SetNull(paymentinvoice.FieldFailedAt)
	return u
}

// SetFailedReason sets the "failed_reason" field.
func (u *PaymentInvoiceUpsert) SetFailedReason(v string) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldFailedReason, v)
	return u
}

// UpdateFailedReason sets the "failed_reason" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateFailedReason() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldFailedReason)
	return u
}

// ClearFailedReason clears the value of the "failed_reason" field.
func (u *PaymentInvoiceUpsert) ClearFailedReason() *PaymentInvoiceUpsert {
	u.SetNull(paymentinvoice.FieldFailedReason)
	return u
}

// SetStorageProvider sets the "storage_provider" field.
func (u *PaymentInvoiceUpsert) SetStorageProvider(v string) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldStorageProvider, v)
	return u
}

// UpdateStorageProvider sets the "storage_provider" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateStorageProvider() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldStorageProvider)
	return u
}

// SetStorageKey sets the "storage_key" field.
func (u *PaymentInvoiceUpsert) SetStorageKey(v string) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateStorageKey() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldStorageKey)
	return u
}

// ClearStorageKey clears the value of the "storage_key" field.
func (u *PaymentInvoiceUpsert) ClearStorageKey() *PaymentInvoiceUpsert {
	u.SetNull(paymentinvoice.FieldStorageKey)
	return u
}

// SetFileName sets the "file_name" field.
func (u *PaymentInvoiceUpsert) SetFileName(v string) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateFileName() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldFileName)
	return u
}

// ClearFileName clears the value of the "file_name" field.
func (u *PaymentInvoiceUpsert) ClearFileName() *PaymentInvoiceUpsert {
	u.SetNull(paymentinvoice.FieldFileName)
	return u
}

// SetContentType sets the "content_type" field.
func (u *PaymentInvoiceUpsert) SetContentType(v string) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateContentType() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldContentType)
	return u
}

// ClearContentType clears the value of the "content_type" field.
func (u *PaymentInvoiceUpsert) ClearContentType() *PaymentInvoiceUpsert {
	u.SetNull(paymentinvoice.FieldContentType)
	return u
}

// SetByteSize sets the "byte_size" field.
func (u *PaymentInvoiceUpsert) SetByteSize(v int64) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldByteSize, v)
	return u
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateByteSize() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldByteSize)
	return u
}

// AddByteSize adds v to the "byte_size" field.
func (u *PaymentInvoiceUpsert) AddByteSize(v int64) *PaymentInvoiceUpsert {
	u.Add(paymentinvoice.FieldByteSize, v)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *PaymentInvoiceUpsert) SetSha256(v string) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateSha256() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldSha256)
	return u
}

// ClearSha256 clears the value of the "sha256" field.
func (u *PaymentInvoiceUpsert) ClearSha256() *PaymentInvoiceUpsert {
	u.SetNull(paymentinvoice.FieldSha256)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentInvoiceUpsert) SetUpdatedAt(v time.Time) *PaymentInvoiceUpsert {
	u.Set(paymentinvoice.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsert) UpdateUpdatedAt() *PaymentInvoiceUpsert {
	u.SetExcluded(paymentinvoice.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentInvoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentInvoiceUpsertOne) UpdateNewValues() *PaymentInvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentinvoice.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentInvoice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentInvoiceUpsertOne) Ignore() *PaymentInvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentInvoiceUpsertOne) DoNothing() *PaymentInvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentInvoiceCreate.OnConflict
// documentation for more info.
func (u *PaymentInvoiceUpsertOne) Update(set func(*PaymentInvoiceUpsert)) *PaymentInvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentInvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentInvoiceUpsertOne) SetUserID(v int64) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateUserID() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateUserID()
	})
}

// SetTitleName sets the "title_name" field.
func (u *PaymentInvoiceUpsertOne) SetTitleName(v string) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetTitleName(v)
	})
}

// UpdateTitleName sets the "title_name" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateTitleName() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateTitleName()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *PaymentInvoiceUpsertOne) SetTaxID(v string) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateTaxID() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateTaxID()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentInvoiceUpsertOne) SetStatus(v string) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateStatus() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *PaymentInvoiceUpsertOne) SetRequestedAt(v time.Time) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateRequestedAt() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateRequestedAt()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *PaymentInvoiceUpsertOne) SetIssuedAt(v time.Time) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateIssuedAt() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *PaymentInvoiceUpsertOne) ClearIssuedAt() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearIssuedAt()
	})
}

// SetFailedAt sets the "failed_at" field.
func (u *PaymentInvoiceUpsertOne) SetFailedAt(v time.Time) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetFailedAt(v)
	})
}

// UpdateFailedAt sets the "failed_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateFailedAt() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateFailedAt()
	})
}

// ClearFailedAt clears the value of the "failed_at" field.
func (u *PaymentInvoiceUpsertOne) ClearFailedAt() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearFailedAt()
	})
}

// SetFailedReason sets the "failed_reason" field.
func (u *PaymentInvoiceUpsertOne) SetFailedReason(v string) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetFailedReason(v)
	})
}

// UpdateFailedReason sets the "failed_reason" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateFailedReason() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateFailedReason()
	})
}

// ClearFailedReason clears the value of the "failed_reason" field.
func (u *PaymentInvoiceUpsertOne) ClearFailedReason() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearFailedReason()
	})
}

// SetStorageProvider sets the "storage_provider" field.
func (u *PaymentInvoiceUpsertOne) SetStorageProvider(v string) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetStorageProvider(v)
	})
}

// UpdateStorageProvider sets the "storage_provider" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateStorageProvider() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateStorageProvider()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *PaymentInvoiceUpsertOne) SetStorageKey(v string) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateStorageKey() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateStorageKey()
	})
}

// ClearStorageKey clears the value of the "storage_key" field.
func (u *PaymentInvoiceUpsertOne) ClearStorageKey() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearStorageKey()
	})
}

// SetFileName sets the "file_name" field.
func (u *PaymentInvoiceUpsertOne) SetFileName(v string) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateFileName() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateFileName()
	})
}

// ClearFileName clears the value of the "file_name" field.
func (u *PaymentInvoiceUpsertOne) ClearFileName() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearFileName()
	})
}

// SetContentType sets the "content_type" field.
func (u *PaymentInvoiceUpsertOne) SetContentType(v string) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateContentType() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateContentType()
	})
}

// ClearContentType clears the value of the "content_type" field.
func (u *PaymentInvoiceUpsertOne) ClearContentType() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearContentType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *PaymentInvoiceUpsertOne) SetByteSize(v int64) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *PaymentInvoiceUpsertOne) AddByteSize(v int64) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateByteSize() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateByteSize()
	})
}

// SetSha256 sets the "sha256" field.
func (u *PaymentInvoiceUpsertOne) SetSha256(v string) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateSha256() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateSha256()
	})
}

// ClearSha256 clears the value of the "sha256" field.
func (u *PaymentInvoiceUpsertOne) ClearSha256() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearSha256()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentInvoiceUpsertOne) SetUpdatedAt(v time.Time) *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertOne) UpdateUpdatedAt() *PaymentInvoiceUpsertOne {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentInvoiceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentInvoiceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentInvoiceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentInvoiceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentInvoiceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentInvoiceCreateBulk is the builder for creating many PaymentInvoice entities in bulk.
type PaymentInvoiceCreateBulk struct {
	config
	err      error
	builders []*PaymentInvoiceCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentInvoice entities in the database.
func (_c *PaymentInvoiceCreateBulk) Save(ctx context.Context) ([]*PaymentInvoice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentInvoice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentInvoiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentInvoiceCreateBulk) SaveX(ctx context.Context) []*PaymentInvoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentInvoiceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentInvoiceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentInvoice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentInvoiceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentInvoiceCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentInvoiceUpsertBulk {
	_c.conflict = opts
	return &PaymentInvoiceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentInvoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentInvoiceCreateBulk) OnConflictColumns(columns ...string) *PaymentInvoiceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentInvoiceUpsertBulk{
		create: _c,
	}
}

// PaymentInvoiceUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentInvoice nodes.
type PaymentInvoiceUpsertBulk struct {
	create *PaymentInvoiceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentInvoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentInvoiceUpsertBulk) UpdateNewValues() *PaymentInvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentinvoice.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentInvoice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentInvoiceUpsertBulk) Ignore() *PaymentInvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentInvoiceUpsertBulk) DoNothing() *PaymentInvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentInvoiceCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentInvoiceUpsertBulk) Update(set func(*PaymentInvoiceUpsert)) *PaymentInvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentInvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentInvoiceUpsertBulk) SetUserID(v int64) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateUserID() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateUserID()
	})
}

// SetTitleName sets the "title_name" field.
func (u *PaymentInvoiceUpsertBulk) SetTitleName(v string) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetTitleName(v)
	})
}

// UpdateTitleName sets the "title_name" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateTitleName() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateTitleName()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *PaymentInvoiceUpsertBulk) SetTaxID(v string) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateTaxID() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateTaxID()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentInvoiceUpsertBulk) SetStatus(v string) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateStatus() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *PaymentInvoiceUpsertBulk) SetRequestedAt(v time.Time) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateRequestedAt() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateRequestedAt()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *PaymentInvoiceUpsertBulk) SetIssuedAt(v time.Time) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateIssuedAt() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *PaymentInvoiceUpsertBulk) ClearIssuedAt() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearIssuedAt()
	})
}

// SetFailedAt sets the "failed_at" field.
func (u *PaymentInvoiceUpsertBulk) SetFailedAt(v time.Time) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetFailedAt(v)
	})
}

// UpdateFailedAt sets the "failed_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateFailedAt() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateFailedAt()
	})
}

// ClearFailedAt clears the value of the "failed_at" field.
func (u *PaymentInvoiceUpsertBulk) ClearFailedAt() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearFailedAt()
	})
}

// SetFailedReason sets the "failed_reason" field.
func (u *PaymentInvoiceUpsertBulk) SetFailedReason(v string) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetFailedReason(v)
	})
}

// UpdateFailedReason sets the "failed_reason" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateFailedReason() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateFailedReason()
	})
}

// ClearFailedReason clears the value of the "failed_reason" field.
func (u *PaymentInvoiceUpsertBulk) ClearFailedReason() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearFailedReason()
	})
}

// SetStorageProvider sets the "storage_provider" field.
func (u *PaymentInvoiceUpsertBulk) SetStorageProvider(v string) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetStorageProvider(v)
	})
}

// UpdateStorageProvider sets the "storage_provider" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateStorageProvider() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateStorageProvider()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *PaymentInvoiceUpsertBulk) SetStorageKey(v string) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateStorageKey() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateStorageKey()
	})
}

// ClearStorageKey clears the value of the "storage_key" field.
func (u *PaymentInvoiceUpsertBulk) ClearStorageKey() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearStorageKey()
	})
}

// SetFileName sets the "file_name" field.
func (u *PaymentInvoiceUpsertBulk) SetFileName(v string) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateFileName() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateFileName()
	})
}

// ClearFileName clears the value of the "file_name" field.
func (u *PaymentInvoiceUpsertBulk) ClearFileName() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearFileName()
	})
}

// SetContentType sets the "content_type" field.
func (u *PaymentInvoiceUpsertBulk) SetContentType(v string) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateContentType() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateContentType()
	})
}

// ClearContentType clears the value of the "content_type" field.
func (u *PaymentInvoiceUpsertBulk) ClearContentType() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearContentType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *PaymentInvoiceUpsertBulk) SetByteSize(v int64) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *PaymentInvoiceUpsertBulk) AddByteSize(v int64) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateByteSize() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateByteSize()
	})
}

// SetSha256 sets the "sha256" field.
func (u *PaymentInvoiceUpsertBulk) SetSha256(v string) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateSha256() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateSha256()
	})
}

// ClearSha256 clears the value of the "sha256" field.
func (u *PaymentInvoiceUpsertBulk) ClearSha256() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.ClearSha256()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentInvoiceUpsertBulk) SetUpdatedAt(v time.Time) *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentInvoiceUpsertBulk) UpdateUpdatedAt() *PaymentInvoiceUpsertBulk {
	return u.Update(func(s *PaymentInvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentInvoiceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentInvoiceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentInvoiceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentInvoiceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
